### PR TITLE
Update instructions.md

### PR DESCRIPTION
**Pull request by 7c6f434c**
I think I want to have the notifications in «participating» group at GitHub

### CODE REVIEW

**Comment by grahamc** [comment]
Yay! Very glad to have you :D

**Comment by 7c6f434c** [comment]
>Yay! Very glad to have you :D

I didn't promise to change anything about my participation and I am not
asking to join the GitHub NixOS-security team. As I said, a purely 
interface decision. A lot of roundups include at least one package 
I have touched relatively recently anyway…

**Comment by grahamc** [comment]
I know :) this isn't any additional commitment. None the less, I'm glad to have you!

**Comment by 7c6f434c** [comment]
Yes, this is more about organising my commitment to NixPkgs caused by
a bit of lock-in…

**Pull request merged**
